server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: customer

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: Witsuta Onampai
    password: test1234

  security:
    user:
      name: Witsuta Onampai
      password: test1234
      roles: admin